name: Update Backend from JTS Index

on:
  repository_dispatch:
    types: [index_updated]
  workflow_dispatch: # Manual trigger option

jobs:
  sync-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout specwork_dashboard
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout JTS repository  
        uses: actions/checkout@v4
        with:
          repository: ddoachi/jts
          path: jts-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Parse JTS index.md and extract data
        run: |
          echo "Processing updated index.md from JTS repository..."
          echo "JTS commit: ${{ github.event.client_payload.commit }}"
          echo "Timestamp: ${{ github.event.client_payload.timestamp }}"
          
          # Copy JTS specs data for processing
          cp -r jts-repo/specs ./jts-specs
          
          # Parse the JTS specs to generate data for our backend
          yarn run parse:specs -- --source=jts-specs
          
      - name: Update backend database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_URL: ${{ secrets.API_URL }}
          SYNC_API_KEY: ${{ secrets.SYNC_API_KEY }}
        run: |
          echo "Syncing JTS spec data to specwork_dashboard backend..."
          yarn run sync:database